name: Publish to PyPI

# 触发条件：推送新的 tag 时运行
on:
  push:
    tags:
    - 'v*.*.*' # 匹配类似 v0.1.0 的版本号

jobs:
  publish:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行环境

    steps:
    # 1. 拉取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3.x 版本

    # 3. 安装构建和上传工具
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    # 4. 构建包
    - name: Build package
      run: python -m build

    # 5. 上传到 PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }} # PyPI 用户名
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }} # PyPI API Token
      run: python -m twine upload dist/*
